// Datos extraídos directamente de las 74 plantillas reales F-01-P-SM01 (carpeta
// MANTENIMIENTOS / Formatos Mantenimientos Preventivos de Drive). Cada equipo trae su
// checklist de "Descripción de los procedimientos realizados" tal como aparece en la
// plantilla original. Si agregas una plantilla nueva en Drive, añade una entrada nueva
// aquí con el mismo formato, y su ID de archivo en TEMPLATE_FILE_IDS más abajo.

const EQUIPOS_DATA = {
  "Agitador de Mazzini": [
    "Revision de condición física y operativa del motor.",
    "Revisión y lubricación de mecanismo rotador.",
    "Revisión y limpieza de tarjeta electrónica controladora de velocidad.",
    "Revisión de control de velocidad.",
    "Verificación de correcto funcionamiento.",
    "Revisión de temporizador.",
  ],
  "Alcoholímetro": [
    "Revisión de condicion física y operativa de teclado y display.",
    "Verificación de lectura al exhalar en él.",
    "Revisión de conducto de medición.",
    "Revisión de condición física de boquillas",
  ],
  "Aspirador": [
    "Revisión de mangueras internas.",
    "Revisión de cable AC.",
    "Comprobación de funcionamiento de manómetro.",
    "Comprobación de funcionamiento de botón de encendido.",
    "Comprobación de regulación de presión de succión.",
    "Pruebas de fugas.",
    "Revisión conexiones eléctricas interiores.",
    "Revisión de estado de filtro de entrada de aire.",
  ],
  "Autoclave de vapor": [
    "Revisión de correcto funcionamiento de electroválvula.",
    "Revisión de correcto funcionamiento de display.",
    "Revisión de sistema eléctrico.",
    "Revisión de condición físicadel tanque de esterilizacion.",
    "Revisión de integridad de sello de puerta.",
    "Revisión de condición operativa de mandos de control.",
    "Puesta en marcha para comprobar correcto funcionamiento de ciclo de esterilización.",
  ],
  "Autoclave de vapor para odontología": [
    "Comprobación de correcto funcionamiento.",
    "Revisión sistema de tuberías",
    "Revisión sistema eléctrico, resistencias y termostato",
    "Revisión de fucionamiento de manómetro de presión.",
    "Comprobación de autonomía de batería",
    "Revisión de funcionamiento de pilotos",
    "Revisión de opeación de válvula solenoide llenado de agua y evacuación.",
    "Revisión de puerta y empaque de sellado",
    "Comprobación de control de presión y temperatura programada.",
    "Revisión de funcionamiento de timer",
  ],
  "Bomba de infusión": [
    "Se verifica el estado fisico de la pantalla y las teclas",
    "Se verifica el  correcto funcionamiento del sistema de cierre y apertura de las puertas",
    "Se verifica el correcto funcionamiento de la función bolo",
    "Se verifica el correcto funcionamieno de las alarmas",
    "Se realiza prueba de tasa de infusión (Valor programado VS Valor infundido)",
  ],
  "Báscula Análoga": [
    "Revisión del correcto estado físico de platinas distribuidoras de peso.",
    "Revisión del correcto estado físico y operativo de sistema puesta cero.",
    "Revisión de condición física del disco graduado.",
    "Revisión del correcto estado físico y operativo de resorte encargado de giro aguja.",
    "Revisión de condición física y operativa del sistema mecánico.",
    "Pruebas de correcto funcionamiento al aplicar peso en ella.",
    "Revisión de integridad de estructura.",
  ],
  "Báscula Análoga con tallímetro": [
    "Revisión del correcto estado físico de platinas distribuidoras de peso.",
    "Revisión de correcto desplazamiento del tallímetro telescópico.",
    "Revisión de buen estado fisico y operativo de barra medidora de estatura.",
    "Revisión de condición física del pesas medidoras.",
    "Revisión de condición física y operativa del sistema mecánico.",
    "Pruebas de correcto funcionamiento al aplicar peso en ella.",
    "Revisión de integridad de estructura.",
  ],
  "Báscula Colgante": [
    "Se comprueba correcto funcionamiento de display",
    "Comprobación de funcionamiento deL sensor de peso",
    "Comprobación de correcto funcionamiento de batería",
    "Inspección y lilmpieza de contactos de baterías",
    "Comprobación de correcto funcionamiento de cambio de unidades",
    "Lectura de voltaje de batería.",
  ],
  "Báscula Digital": [
    "Revisión de funcionamiento individual de galgas de presión",
    "Comprobación de correcto funcionamiento de display",
    "Revisión de conexiones eléctricas y función de auto encendido.",
    "Comprobación de funcionamiento de pulsador de cambio de unidades.",
    "Revisión de compartimento de baterías.",
    "Pruebas de funcionamiento general.",
  ],
  "Báscula Digital pesa bebé": [
    "Revisión de funcionamiento individual de galgas de presión",
    "Comprobación de correcto funcionamiento de display",
    "Revisión de conexiones eléctricas y función de auto encendido.",
    "Comprobación de funcionamiento de pulsador de cambio de unidades.",
    "Revisión de compartimento de baterías.",
    "Revisión de condición física de bandeja.",
    "Pruebas de funcionamiento general.",
  ],
  "Báscula Industrial": [
    "Revisión de funcionamiento  de galga de presión",
    "Comprobación de correcto funcionamiento de display",
    "Revisión de conexiones eléctricas y función de auto encendido.",
    "Comprobación de funcionamiento de pulsador de cambio de unidades.",
    "Revisión de compartimento de baterías.",
    "Pruebas de funcionamiento general.",
  ],
  "CPAP": [
    "Inspección de condición física de circuito neumático interno.",
    "Revisión de de condición física de botones de control.",
    "Revisión de condición física de tarjeta electrónica.",
    "Pruebas de funcionamiento de turbina.",
    "Revision de conexiones eléctricas.",
    "Revisión de conector salida de aire.",
    "Revisión de filtro de entrada de aire.",
    "Revisión de espumas internas.",
    "Revisión y limpieza de circuito respiratorio.",
  ],
  "Calentador Eléctrico": [
    "Revisión de integridad física de estructura.",
    "Limpieza de filtro",
    "Revisión de mecanísmo de encendido.",
    "Revisión de teclado y pantalla",
    "Revisión de correcto funcionamiento de aumento y disminución de temperatura",
  ],
  "Cama Eléctrica Hospitalaria": [
    "Revisión de estructura física.",
    "Revisión de sistema eléctrico.",
    "Pruebas de movimientos desde control manual.",
    "Prueba de sistemas de elevación.",
    "Lubricación de articulaciones.",
    "Revisión de desplazamiento y sistema de freno.",
    "Revisión de correcto estado y funcionamiento barandas de seguridad.",
  ],
  "Camilla": [
    "Revisión y ajuste de conexiones eléctricas interiores.",
    "Revisión de correcto encendido de luces.",
    "Revisión y lubricación de articulaciones.",
    "Revisión de correcto estado físico y funcional de motores.",
    "Pruebas de funcionamiento de movimientos.",
    "Pruebas de funcionamiento de pedal.",
  ],
  "Camilla hidraulica": [
    "Revisión de sistema hidraulico.",
    "Busqueda de fugas de aceite en sistema hidraulico.",
    "Revisión y lubricación de articulaciones.",
    "Revisión y limpieza de ruedas",
    "Pruebas de funcionamiento de válvulas para activar elevación y descenso de la camilla.",
    "Pruebas de funcionamiento de pedal.",
  ],
  "Centrifuga": [
    "Revisión de conexiones eléctricas interiores.",
    "Comprobación de funcionamiento de temporizador con cronometraje.",
    "Revisión de correcta regulación de velocidad.",
    "Revisión de nivelación de rotor.",
    "Pruebas de respuesta a vibración en funcionamiento.",
    "Pruebas de funcionamiento general.",
  ],
  "Cinta métrica": [
    "Se verifica la correcta posición vertical.",
    "Se verifica el correcto estado del mecanismo de retracción.",
    "Se verifica el correcto estado de la impresión de la escala.",
    "Se verifica la condición física de la base del tallímetro.",
    "Se verifica la condición física del visor.",
    "Se verifica la condición física de la cinta de medida.",
    "Revisión de deslizamiento suave de la cinta.",
    "Verificación de correcta altura de fijación.",
  ],
  "Compresor de aire": [
    "* Se revisa la condición física del filtro de aire al compresor.",
    "* Se revisa el nivel de aceite del tanque separador.",
    "* Se limpia toda la estructura del todo el sistema de compresión.",
    "* Se revisa la condición física del sistema eléctrica.",
    "* Se revisa el manómetro de presión de aceite.",
  ],
  "Cuna de calor radiante": [
    "Comprobación de correcto funcionamiento.",
    "Revisión de funcionamiento de display e indicadores luminosos",
    "Verificación de activación de alarmas cuando esta la lectura fuera de programación.",
    "Revisión de correcto estado y funcionamiento de sensor paciente.",
    "Comprobación de regulación de temperatura según valores programados.",
    "Verificación de variación de temperatura en resistencia según variación de temperatura en sensor paciente en modo servo.",
    "Verificación de variación de temperatura en resistencia según modificación de porcentaje seleccionado en panel en modo manual.",
    "Revisión de condición física de carcasas.",
    "Revisión de sistema inclinación de cuna.",
    "Revisión de condición física de toma de entrada y salida de oxígeno.",
  ],
  "DEA": [
    "Medición de voltaje de batería.",
    "Revisión de integridad y continuidad de parches.",
    "Comprobación de funcionamiento de botones e indicadores visuales.",
    "Comprobación de correcta activación de instrucciones.",
    "Pruebas para detección de arritmias y ecg normal.",
    "Pruebas de desfibrilación con analizador de energía.",
  ],
  "Desfibrilador": [
    "Comprobación de correcta lectura de ecg.",
    "Comprobación de detección de onda QRS y de arritmias.",
    "Pruebas de funcionamiento e integridad de mandos de control.",
    "Revisión de correcto funcionamiento de pantalla.",
    "Pruebas de detección de palas y parches de desfibrilación.",
    "Pruebas de continuidad en cable ecg, parches  y palas.",
    "Prueba de autonomía de batería.",
    "Test de funcionamiento general.",
    "Mediciones cuantitativas con analizador de desfibrilación.",
  ],
  "Doppler fetal": [
    "Comprobación de correcto encendido.",
    "Revisión funcional de mandos de control.",
    "Revisión de funcionamiento de display.",
    "Revisión de funcionamiento de transductor.",
    "Revisión de estado de batería.",
    "Comprobación de registro de actividad cardiaca y pulso con simulador.",
  ],
  "Electrobisturí": [
    "Verificación de condición física y operativa de panel de control (Suiches y displays).",
    "Verificación de condición física y operativa de conectores para electrodos y pedales.",
    "Verificación de condición física y operativa de pedal monopolar y pedal  bipolar.",
    "Limpieza de ventiladores y tarjetas electrónicas.",
    "Verificación de activación de alarma por no detección de placa dispersiva.",
    "Revisión de conecciones eléctricas internas.",
    "Lectura de potencia monopolar y bipolar entregada por el equipo con analizador de potencia.",
    "Limpieza general.",
  ],
  "Electrocardiógrafo": [
    "Revisión de carga de batería.",
    "Revisión de estado físico y funcional de pulsadores de control.",
    "Revisión de estado físico y funcional de pantalla.",
    "Revisión de puertos de entrada de cable de ecg y cable AC",
    "Comprobación de funcionamiento manual y automático de impresión.",
    "Revisión de funcionamiento de registrador.",
    "Comprobación de correcta lectura de parámetros con simulador.",
    "Pruebas de ruido e interferencia.",
  ],
  "Equipo de órganos": [
    "Limpieza de contactos de compartimento de baterías de otoscopio y oftalmoscopio.",
    "Comprobación de funcionamiento de reguladores de enfoque y lentes en oftalmoscopio.",
    "Comprobación de encendido de luces con interruptor.",
    "Comprobación estado de baterías.",
    "Comprobación de funcionamiento de mencanismo de encendido.",
    "Revisión y limpieza de contactos de bombillos.",
  ],
  "Esfigmomanómetro": [
    "Comprobación de funcionamiento de manómetro.",
    "Se realiza prueba de fugas.",
    "Revisión de correcto estado de brazalete y mangueras.",
    "Comprobación de correcto insuflado.",
    "Comprobación de funcionamiento de válvula de pera.",
  ],
  "Espirómetro": [
    "Comprobación de funcionamiento de display.",
    "Revisipon de condición fisica y operativa del teclado.",
    "Revisión de condición física y operativa de la turbina.",
    "Limpieza de turbina.",
    "Revisón de cable USB.",
    "Lectura de voltaje de pila.",
    "Verificación de lectura  de flujo en display utilizando una jeringa patrón.",
    "Verificación de correctas funciones de operación.",
  ],
  "Flujómetro": [
    "Revisión de o-rings de sellado",
    "Comprobación de fugas.",
    "Comprobación de funcionamiento de válvula reguladora de flujo.",
    "Revisión de conexiones de entrada y salida.",
    "Revisión de funcionamiento de caudalímetro.",
  ],
  "Fonendoscopio": [
    "Inspección de estado físico de campanas.",
    "Revisión de integridad de diafragma y sus componentes.",
    "Revisión de buen estado de mangueras y conexiones,",
    "Revisión de olivas y conductos en busca de obstrucciones.",
    "Pruebas de funcionamiento.",
  ],
  "Fronto Luz": [
    "Revisión sistema enfoque de luz.",
    "Revisión Led.",
    "Reisión de carga batería.",
    "Revisión de cable y conector batería.",
    "Revisión de soporte lente.",
  ],
  "Glucómetro": [
    "Comprobación de funcionamiento de display.",
    "Comprobación de funcionamiento de pulsadores.",
    "Revisión de compartimento de batería y contactos.",
    "Revisión de tarjetas electrónicas.",
    "Comprobación de detección de tiras reactivas.",
    "Comprobación de lectura de parámetros.",
    "Lectura de voltaje de batería.",
  ],
  "Gramera": [
    "Se verifica correcto funcionamiento de display",
    "Se verifica estado físico del equipo",
    "Se verifica el estado físico de la bandeja",
    "Se verifica correcto funcionamiento de modos de pesaje (unidades)",
    "Se realizan pruebas de funcionamiento general",
  ],
  "Incubadora": [
    "Comprobación de correcto funcionamiento.",
    "Revisión de funcionamiento de display e indicadores luminosos",
    "Revisión de correcto estado y funcionamiento de sensores.",
    "Comprobación de regulación de temperatura según valores programados.",
    "Comprobación de autonomía de batería",
    "Revisión de funcionamiento de mandos de control.",
    "Revisión de motor y aspas ventilador",
  ],
  "Laringoscopio": [
    "Se revisa integridad física del mango",
    "Se revisa integridad física de las valvas",
    "Se realiza lectura de voltaje de baterías",
    "Se realiza limpieza de contactos",
    "Se realizan pruebas de funcionamiento general",
  ],
  "Linterna para diagnóstico": [
    "Se verifica el estado fisico del equipo",
    "Revisión de condición física contactos baterías.",
    "Se verifica el sistema de encendido y apagado del equipo",
    "Se verifica el buen funcionamiento del bombillo.",
    "Pruebas de funcionamiento general",
  ],
  "Lámpara Fotocurado": [
    "Revisión de integridad física de estructura.",
    "Revisión de condición física y operativa de teclado",
    "Revisión de condición física de cable AC.",
    "Revisión de condición física y operativa de los leds para fotocurado",
    "Verificación de correcta función de variación de intensidad lumínica.",
  ],
  "Lámpara Fototerapia": [
    "Revisión de integridad física de estructura.",
    "Revisión de condición física y operativa de teclado y display.",
    "Revisión de condición física de cable AC.",
    "Revisión de condición física y operativa de los leds para fototerapia.",
    "Verificación de correcta función de variación de intensidad lumínica.",
    "Revisión de condición fisica y operativa del brazo y sus articulaciones.",
    "Revisión y limpieza de base y ruedas.",
  ],
  "Lámpara cialítica": [
    "Revisión de integridad física de estructura.",
    "Lubricación de articulaciones.",
    "Revisión de mecanísmo de encendido.",
    "Revisión de sistema eléctrico.",
    "Revisión de intensidad de luz.",
  ],
  "Lámpara cuello de cisne": [
    "Se verifica el estado fisico del equipo",
    "Revisión de condición física y operativa del sistema eléctrico.",
    "Se verifica el sistema de encendido y apagado del equipo",
    "Se verifica el buen funcionamiento de la lámpara.",
    "Pruebas de funcionamiento general",
  ],
  "Lámpara infrarroja": [
    "Revisión de condición física del cable AC.",
    "Revisiónn de suiche selector de funciones.",
    "Revisión de leds infrarrojo.",
    "Verificación de activación de motor vibrador.",
    "Revisión de condición física de carcasa.",
  ],
  "Lámpara pielítica": [
    "Revisión de integridad física de estructura.",
    "Lubricación de articulaciones.",
    "Revisión de mecanísmo de encendido.",
    "Revisión de sistema eléctrico.",
    "Revisión de condición operativa de bombillería.",
    "Revisión de condición operativa de enfoque luz.",
  ],
  "Martillo Reflejos": [
    "Revisión de condición física de las puntas de caucho.",
    "Revisión de condición física de punzon y cepillo .",
    "Revisión de condición física  y limpieza de estructura.",
  ],
  "Mesa de cirugía": [
    "* Revisión general de estructura y accesorios.",
    "* Verificación de estabilidad",
    "* Revisión  de movimientos suaves de articulaciones.",
    "* Verificación de activación de todos los movimientos desde el control remoto.",
    "* Verificación de correcta lubricación de las piezas móviles.",
    "* Verificación de correcto funcionamiento del freno.",
    "* Verificación de la elevación y descenso adecuado de la mesa.",
    "* Verificación de ausencia de fuga de líquido hidraulico y correcto funcionamiento de la bomba hidraulica.",
    "* Verificación de funcionamiento general con batería.",
  ],
  "Micromotor": [
    "Revisión de tarjeta controladora de velocidad.",
    "Revisión de condición operativa de suiches.",
    "Revisión de cable micromotor.",
    "Revisión de condición física y operativa del pedal.",
    "Revisión y limpieza de carcasa.",
    "Cambio de rodamientos de punta micromotor.",
    "Verificación de correcta operación del equipo.",
  ],
  "Micropipetas": [
    "Se revisa la integridad de la estructura, se inspecciona en busca de fisuras o irregularidades.",
    "Se revisa mecanismo interno, que se pueda mover libremente y con suavidad, incluyendo el pistón.",
    "Se revisa el portapuntas en busca de deformaciones o desgaste, y se verifica que las puntas se ajusten correctamente.",
    "Se lubrica pistón y embolo para asegurar un correcto desplazamiento y buena succión.",
    "Se realiza limpieza interna general.",
    "Se realiza prueba de hermeticidad.",
    "Pruebas de funcionamiento general.",
  ],
  "Monitor de signos vitales": [
    "Revisión de correcto funcionamiento de pantalla táctil.",
    "Revisión de correcto estado de accesorios.",
    "Comprobación de funcionamiento de mandos de control.",
    "Verificación de correcta lectura de parametros con simulador paciente.",
    "Pruebas de detección de arritmias cardiacas.",
    "Prueba de fugas en NIBP.",
    "Comprobación de buen funcionamiento de batería.",
    "Revisión de correcta activación de alarmas visuales y sonoras.",
    "Calibración ECG",
  ],
  "Máquina de anestesia": [
    "Revisión de funcionamiento de botones y mando de control",
    "Revisión de funcionamiento de alarmas sonoras y visuales",
    "Pruebas de fugas en modo de ventilación mecánica y ventilación manual",
    "Ajuste de sensor de oxígeno al 21% y al 100%",
    "Revisión de funcionamiento de caudalímetros",
    "Revisión de indicador de manómetros de presión",
    "Limpieza general del equipo",
    "Pruebas de ciclado del ventilador y lectura de parámetros con equipo patrón",
  ],
  "Módulo AG BIS": [
    "* Revisión de ausencia de golpes, grietas o deformaciones de carcasa.",
    "* Revisión de correcto estado físico  del conector al cable de electrodos.",
    "* Revisión de correcto estado físico y operativo del cable de electrodos.",
    "* Limpieza de carcasa y cable electrodos.",
    "* Verificación de conexión firme del cable al conector al insertar y retirar del conector.",
    "* Verificación de reconocimiento del módulo en la máquina de anestesia.",
    "* Verificación de disponibilidad de menú en pantalla de máquina de anestesia.",
    "* Verificación ausencia de mensajes de error en pantalla de máquina de anestesia.",
  ],
  "Módulo NMT": [
    "* Revisión de ausencia de golpes, grietas o deformaciones de carcasa.",
    "* Revisión de correcto estado físico  del conector al cable de electrodos.",
    "* Revisión de correcto estado físico y operativo del cable de electrodos.",
    "* Limpieza de carcasa y cable electrodos.",
    "* Verificación de reconocimiento del módulo en la máquina de anestesia.",
    "* Verificación de disponibilidad de menú en pantalla de máquina de anestesia.",
    "* Verificación ausencia de mensajes de error en pantalla de máquina de anestesia.",
  ],
  "Nebulizador": [
    "Inspección de condición física de circuito neumático interno.",
    "Revisión de interruptor de encendido.",
    "Pruebas de funcionamiento de compresor interno.",
    "Revision de conexiones eléctricas.",
    "Revisión de conector salida de aire.",
    "Revisión de filtro de entrada de aire.",
  ],
  "Negatoscopio": [
    "Se verifica el estado fisico del equipo",
    "Se verifica el sistema de alimentación del equipo",
    "Se verifica el sistema de encendido y apagado del equipo",
    "Se verifica el buen funcionamiento de luces internas",
    "Pruebas de funcionamiento general",
  ],
  "Neopuff": [
    "Revisión de conexión de entrada de oxígeno",
    "Comprobación de correcta salida de oxígeno",
    "Comprobación de funcionamiento de reguladores de presión.",
    "Revisión de circuito neumático interior.",
  ],
  "Nevera": [
    "Medición de corriente de manejo del compresor.",
    "Limpieza de ventiladores tanto del condesador como del evaporador.",
    "Limpieza de condensador y evaporador.",
    "Revisión del sistema de drenaje.",
    "Revisión del sistema eléctrico.",
    "Revisión y limpieza de cámara de frío.",
  ],
  "Optivisor": [
    "Se verifica la condición física de los lentes y su soporte.",
    "Se verifica la condición física del contacto de conexión con la fuente de voltaje.",
    "Se verifica el correcto funcionamiento del suiche de la lámpara led.",
    "Se verifica la condición física y operativa de los soportes laterales.",
    "Se verifica la condición física y operativa del mecanismo de giro del visor.",
    "Se verifica la condición operativa de la lámpara led.",
  ],
  "Picoflujo": [
    "Limpieza de boquilla y superficies externas.",
    "Inspección de estructura  y cubierta para detectar fisuras.",
    "Verificación de desplazamiento del indicador deslizable al aplicar un flujo de aire por la boquilla.",
    "Verificación de desplazamiento de indicadores de límites.",
    "Revisión de piezas móviles de cubierta articulada.",
  ],
  "Pulsioxímetro": [
    "Comprobación de funcionamiento de pantalla.",
    "Comprobación de correcto funcionamiento de pulsador de control.",
    "Revisión de correcto estado de mecanismo de cierre.",
    "Lectura de voltaje de baterías.",
    "Revisión de correcto funcionamiento de las opciones del menú",
    "Pruebas de funcionamiento general",
  ],
  "Regulador O2": [
    "Revisión de o-rings de sellado",
    "Comprobación de fugas.",
    "Comprobación de funcionamiento de válvula reguladora de flujo.",
    "Revisión de conexiones de entrada y salida.",
    "Revisión de funcionamiento de manómetro",
  ],
  "Regulador de vacio": [
    "Se veririfca el funcionamiento de la posición Off",
    "Se veririfca el funcionamiento de la posición Reg",
    "Se veririfca el funcionamiento de la posición Full",
    "Se verifica el funcionamiento de la perilla reguladora de vacio",
    "Se verifica correcto funcionamiento del manómetro de presión negativa",
    "Se verifica buen estado físico",
  ],
  "Silla para procedimientos": [
    "Revisión de estructura física.",
    "Revisión de sistema eléctrico.",
    "Revisión de condición física de cojines.",
    "Pruebas funcionales de los motores de elevación y espaldar.",
    "Lubricación de articulaciones.",
    "Revisión de suiches para movimientos.",
  ],
  "Tanque Hydrocollator": [
    "Comprobación de buen estado de estructura física",
    "Revisión de conexiones eléctricas",
    "Comprobación de funcionamiento del termostato",
    "Revisión de condición física y funcional de la resistencia",
    "Pruebas de funcionamiento general",
  ],
  "Tens": [
    "Revisión y limpieza de tarjeta electrónica",
    "Limpieza de contactos de compartimiento de batería",
    "Revisión de correcto funcionamiento de control de intensidad",
    "Revisión de correcto funcionamiento de control de frecuencia",
    "Revisión de conexiones de salida",
    "Revisión de continuidad de cables de electrodos",
    "Revisión de integridad de la carcasa",
    "Puebas  de funcionamiento general",
  ],
  "Tensiómetro Digital": [
    "Revisión de correcto estado de brazaletes y mangueras.",
    "Lectura de voltaje de baterías de alimentación.",
    "Revisión de contactos de batería.",
    "Revisión de conexiones eléctricas.",
    "Revisión de funcionamiento de pulsadores de control.",
    "Revisión de funcionamiento de pantalla",
    "Pruebas de fugas.",
    "Pruebas de funcionamiento general.",
  ],
  "Tensiómetro Mercurio": [
    "Limpieza de mangueras",
    "Limpieza de brazaletes",
    "Limpieza de tubo contenedor de mercurio",
    "Revisión de funcionamiento de manómetro",
    "Revisión de funcionamiento de pera",
    "Revisión de correcto desplazamiento de mercurio",
    "Pruebas de funcionamiento general",
  ],
  "Termohigrómetro": [
    "Revisión de tarjeta electrónica.",
    "Comprobación funcionamiento de display.",
    "Comprobación de lectura de temperatura y humedad.",
    "Comprobación de funcionamiento de mandos de control.",
    "Limpieza de contactos de batería.",
    "Lectura de voltaje de pila.",
  ],
  "Termohigrómetro análogo": [
    "Revisión de condición física y operativa de las agujas y su mecanismo.",
    "Revisión de condición física de cristal y tablero de mediciones.",
    "Revisión de condición física de carcasa.",
    "Comprobación de lectura de temperatura y humedad.",
  ],
  "Termómetro Digital": [
    "Comprobación de funcionamiento de display.",
    "Comprobación de correcto funcionamiento de cambio unidades.",
    "Limpieza de contacto de baterías.",
    "Revisión de estado de batería.",
    "Pruebas de funcionamiento.",
    "Lectura de voltaje de pila.",
  ],
  "Termómetro Digital Nevera": [
    "Comprobación funcionamiento de display.",
    "Comprobación de lectura de temperatura.",
    "Comprobación de funcionamiento de mandos de control.",
    "Revisión de cable sonda temperatura.",
  ],
  "Termómetro infrarrojo": [
    "Comprobación de funcionamiento de display.",
    "Comprobación de correcto funcionamiento de cambio unidades.",
    "Limpieza de contacto de baterías.",
    "Revisión de estado de batería.",
    "Pruebas de funcionamiento.",
    "Lectura de voltaje de pila.",
  ],
  "Ultrasonido": [
    "Revisión de condición física y operativa de carcasa y pantalla",
    "Revisión de correcto funcionamiento de estimulación por ultrasonido y sus funciones",
    "Revisión de condición física y operativa de aplicador y cable",
    "Revisión de integridad de cable AC",
    "Revisión de conector de cable aplicador",
    "Verificación de funcionamiento del ultrasonido en el aplicador con liquido de forma visual en diferentes frecuencias",
  ],
  "Vacuometro": [
    "Comprobación de fugas.",
    "Comprobación de funcionamiento de válvula reguladora de vacío.",
    "Revisión de conexiones de entrada y salida.",
    "Verificación de correcto desplazamiento de la aguja del manómetro de vacío.",
    "Limpieza de parte interna y su sello.",
    "Verificación de correcto funcionamiento de suiche ON/OFF.",
  ],
  "Ventilador Mecánico": [
    "Revisión de correcto funcionamiento de pantalla  y de sistema táctil.",
    "Revisión de integridad de válvula exhalatoria.",
    "Revisión de integridad de sensores de flujo y línea proximal.",
    "Revisión y limpieza de filtro de entrada.",
    "Se realiza el test inicial de fugas y de  comprobación de válvulas y sensores.",
    "Pruebas de correcto ciclado del ventilador.",
    "Revisión de correcta activación de alarmas sonoras y visuales.",
  ],
  "Ventilador portatil": [
    "Revisión de correcto funcionamiento de pantalla  y de sistema táctil.",
    "Revisión de integridad de válvula exhalatoria.",
    "Revisión de integridad de sensores de flujo y línea proximal.",
    "Revisión y limpieza de filtro de entrada.",
    "Se realiza el test inicial de fugas y de  comprobación de válvulas y sensores.",
    "Pruebas de correcto ciclado del ventilador.",
    "Revisión de correcta activación de alarmas sonoras y visuales.",
  ],
  "Otro / personalizado": []
};

// Lista ordenada alfabéticamente para el selector
const EQUIPOS_LISTA = Object.keys(EQUIPOS_DATA).sort((a, b) => a.localeCompare(b, 'es'));

// IDs reales de los archivos de plantilla en Drive (carpeta "Formatos Mantenimientos
// Preventivos" dentro de MANTENIMIENTOS). Los 74 equipos ya están enlazados con su
// plantilla oficial real.
const TEMPLATE_FILE_IDS = {
  "Agitador de Mazzini": "1ZMx_WyhvATjO2aY58akBe_SfdYEftjcz",
  "Alcoholímetro": "1sKppMBQDRII3Cq2QW-gvbKPL-J82H9ib",
  "Aspirador": "13lqdmq_yROqFO95SVWBvcWjh2ie7A2FO",
  "Autoclave de vapor": "1Nf4XEJwIKXiSz6xeGicsLrngK6nxaxab",
  "Autoclave de vapor para odontología": "1_77uHatmhgqzZ6LEhC9GF_xdDtcLTK3k",
  "Bomba de infusión": "1ZVvuh2yLLNG5NaU46SAarqnmh670ehxu",
  "Báscula Análoga": "10eRSbnr9RRzZuqHs8atSfWLNFUPgiD5t",
  "Báscula Análoga con tallímetro": "1yBMBrJPpNEmP-huoQdxP05jZXLo9va59",
  "Báscula Colgante": "1rBx8XjDE2pA3PpAwAzs5G3qoRQb4uJed",
  "Báscula Digital": "1ydrF3ihAYDn4Nna32arqFsTvmW9jN213",
  "Báscula Digital pesa bebé": "1__VwUAlLXT1h5TqYBQFajGd8RCnJnOTY",
  "Báscula Industrial": "14J3iRFTl-gWQ_nCHAnTRUY9GLwNluE6S",
  "CPAP": "1_gC12_A3KdBbyAfFA4AdL9RAnjlryjz0",
  "Calentador Eléctrico": "1BEBwU468yL7w0sqQoxAROpioYY8gTok3",
  "Cama Eléctrica Hospitalaria": "1E0UAgyOUDvOeY-F9Ynv_dhMhnCNizY49",
  "Camilla": "1itOSt3a9kn9A230P-gLgXK_HplRo8D1n",
  "Camilla hidraulica": "1_AsbZfwzJPFLrWNwHLFy2LVExv54OXRO",
  "Centrifuga": "1zbCHucdF5rV0DZ7CbAG2B4dU_uYbX8Bx",
  "Cinta métrica": "1DMJ67Fq7fbRFVSpzaJ9stExC94bqQH_D",
  "Compresor de aire": "1tOCGWF9SNldct7x_pi0KPog37vkNBw2o",
  "Cuna de calor radiante": "1XClN82sdb1m44JRlr7D2LK_4MI5OoYtB",
  "DEA": "1_ddBsfylaRq_pgNSIAemp1oupoYSi6mT",
  "Desfibrilador": "1LerzBk6DccB_EWKBkAo2ZhzRDamI7eNa",
  "Doppler fetal": "1-nMX6lONDG2ihMQjJhUB7ogSezdVVZBi",
  "Electrobisturí": "148sCQbaoYb4BWEopxIFZCWi2AJbgG6Yb",
  "Electrocardiógrafo": "1NhwG5fzKG5S_O1Lm-EIsGGAxE_nfxws8",
  "Equipo de órganos": "1RvHNoU5ZlntY1eYtflANeaF7avjcvQ9n",
  "Esfigmomanómetro": "19DirL1HTV6pZNBM29PvgWtHbSTdTgnx0",
  "Espirómetro": "1_oaFSz2tnLWj1TZIiS2T5Jle2K0jsp9r",
  "Flujómetro": "14WOzZrJ5l6-l5K8vqNrlAGIiJyq8XCPd",
  "Fonendoscopio": "12wJ8SdLmXZjN8WpD0JRm09t_07YBQEZq",
  "Fronto Luz": "15nQfXLFDijZ2JeP2h1WAX3tuaC3Lxz9A",
  "Glucómetro": "1ixRL4FGK1BmaqkYLjbZJWImcMTTjQDNk",
  "Gramera": "1WdvViYWZJGl-awGTS2d7OupgjRhV4Cov",
  "Incubadora": "1bdjz72fzI5_Dfp6p8sVu9JyHt_sth5KV",
  "Laringoscopio": "1MD6O_JOjY3JU1QfQCb3woqscNF58HUhP",
  "Linterna para diagnóstico": "1ZT_Sd7kDEc6jsakNOjv4IefzTK77j5ON",
  "Lámpara Fotocurado": "19Bmt0sKqAa5njZJh03BoM_vpyWx5229J",
  "Lámpara Fototerapia": "1jxY0D4q55d6C50dcWpb1z8-H7TsKX9ro",
  "Lámpara cialítica": "1Lv8Frake355JwjrpIS4GiznItAsweiUA",
  "Lámpara cuello de cisne": "1cb0Bk2TLwjqX-A38AIqOtQI5d_JqkZL1",
  "Lámpara infrarroja": "1WD_0arWXWaABNsXGEdjhuL4fGjTb-Ddv",
  "Lámpara pielítica": "1p_yAPBYV5oIgeXisk_7d3EMbYXmWMOim",
  "Martillo Reflejos": "10klmQvP3N6mZOf66_Aw4phUTFqOM_FS2",
  "Mesa de cirugía": "1aOsP_3m0YUpxZY5sibAztrCkndsxNJ_t",
  "Micromotor": "1r4ytQnIvhDwjUGprHDAme6ziE8vPw6HP",
  "Micropipetas": "1aGBwUIaBBQSjjSCyT50NLeq0eDZWL3tW",
  "Monitor de signos vitales": "1WEsx91ojI9d-mIbiR_Yrzunf7Zlvgrmw",
  "Máquina de anestesia": "1A8nmio-aeLoXR9Lmpu7BnZi8r9S3OpG8",
  "Módulo AG BIS": "1pcJygyvQKclPkrYFTH-rgT6iZP1HaajD",
  "Módulo NMT": "1Bv14Jvc4H8g0ODjLqpV0qBzxvZ2C52IG",
  "Nebulizador": "1s_BAINPeQs2zuOEIXWjs-G1dXfenCp98",
  "Negatoscopio": "1Lm2hxJ0K4YCZiRY4NGhtWJ9zLOBq1KYr",
  "Neopuff": "1Fk2wGldiw6Q1nFePHVcY1ygz8_vl5TwF",
  "Nevera": "18R5FBoxH8Xc4uoquIvBOh9XJ8E6v2mBO",
  "Optivisor": "1rYlyYbXmbJLXp4F2We-gn3iPLNvtvWOT",
  "Picoflujo": "1XfxScXKAINuWopOGB4_iuIigHQaLay2i",
  "Pulsioxímetro": "1Le_rNmavtINDglnBsZMbxHFLtWizEkeD",
  "Regulador O2": "1rs8_8fXUo21lm5Soy4Kgz8s1OF8IqjbO",
  "Regulador de vacio": "1RJJ2q7YE--_kpl4YdiOJTUFtE0oBua8I",
  "Silla para procedimientos": "1ljMWKNkBOCAqd8WhPHlsE5MTNv4RRcO3",
  "Tanque Hydrocollator": "19sxkLDdQgxzda5aR7DoV3SOIlToXHMBL",
  "Tens": "1cnAlfLq8bKnJIjcEMN1HnRcSaD3gbyEF",
  "Tensiómetro Digital": "1AWOtct1xiTmmixejJEjMPXLE1vRptNzL",
  "Tensiómetro Mercurio": "1JW3QV7GysFJ3qhOf9RLhxNeN5b7Eh6uC",
  "Termohigrómetro": "1Az6Ng3zKeplPs1NGn2Ftyv5Kt2iS6dDg",
  "Termohigrómetro análogo": "1jJ8aqz_auDeu3QVVJCPkXy_t5aNgv33u",
  "Termómetro Digital": "13Ih3cT2paS8jOc6r92n0TIERxCJc5iCT",
  "Termómetro Digital Nevera": "1sUpxa0OPE5TjIIuK_dQlThoROoROHtD4",
  "Termómetro infrarrojo": "1IHdLGWUal2iBbISqSsSl9G-KiENDCHsG",
  "Ultrasonido": "1WrhOeZy7AHjc3LVBQgDhj2PpzLXVJRty",
  "Vacuometro": "1Iv4dZUWFIB4UQFhqM6oQ5UzfMqK1VimX",
  "Ventilador Mecánico": "1SZ4YXHQYXIxIenVadzLu3x51DKRCI2Cq",
  "Ventilador portatil": "1CSL1ag4bknthXKG6S6YxLuEDSHe3N8C5"
};
